export type DailyListInfoType = {
  id: number;
  ImageUrl: string;
  Like: number;
  Title: string;
  Writer: string;
  Date: Date;
  Comment: number;
  Tags: string[];
};
let id = 1;
let Like = 1;
export const dailyListInfo: DailyListInfoType[] = [
  // 80개 만들어놨음
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title:
      '제목 테스트 해야함 너무 길면 잘라야함. 잘라지나확인해보자@@@@@@@@@@@@',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: [
      '#인천',
      '#여행',
      '#태그가 길어지면 자르지말고 그냥 길게',
      '#태그가 길어지면 자르지말고 그냥 길게',
      '#태그',
      '#태그',
      '#태그',
    ],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title: '우선 Like 수로 페이지네이션 확인해봄 1씩증가',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행'],
  },
  {
    id: id++,
    ImageUrl: '',
    Like: Like++,
    Title: '총 데이터는 80개로 만들어놨음. 10개씩, 8페이지',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행', '#태그'],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행'],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title:
      '제목 테스트 해야함 너무 길면 잘라야함. 잘라지나확인해보자@@@@@@@@@@@@',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: [
      '#인천',
      '#여행',
      '#태그가 길어지면 자르지말고 그냥 길게',
      '#태그가 길어지면 자르지말고 그냥 길게',
      '#태그',
      '#태그',
      '#태그',
    ],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행'],
  },
  {
    id: id++,
    ImageUrl: '',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행', '#태그'],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행'],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title:
      '제목 테스트 해야함 너무 길면 잘라야함. 잘라지나확인해보자@@@@@@@@@@@@',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: [
      '#인천',
      '#여행',
      '#태그가 길어지면 자르지말고 그냥 길게',
      '#태그가 길어지면 자르지말고 그냥 길게',
      '#태그',
      '#태그',
      '#태그',
    ],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행'],
  },
  {
    id: id++,
    ImageUrl: '',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행', '#태그'],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행'],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title:
      '제목 테스트 해야함 너무 길면 잘라야함. 잘라지나확인해보자@@@@@@@@@@@@',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: [
      '#인천',
      '#여행',
      '#태그가 길어지면 자르지말고 그냥 길게',
      '#태그가 길어지면 자르지말고 그냥 길게',
      '#태그',
      '#태그',
      '#태그',
    ],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행'],
  },
  {
    id: id++,
    ImageUrl: '',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행', '#태그'],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행'],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title:
      '제목 테스트 해야함 너무 길면 잘라야함. 잘라지나확인해보자@@@@@@@@@@@@',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: [
      '#인천',
      '#여행',
      '#태그가 길어지면 자르지말고 그냥 길게',
      '#태그가 길어지면 자르지말고 그냥 길게',
      '#태그',
      '#태그',
      '#태그',
    ],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행'],
  },
  {
    id: id++,
    ImageUrl: '',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행', '#태그'],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행'],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title:
      '제목 테스트 해야함 너무 길면 잘라야함. 잘라지나확인해보자@@@@@@@@@@@@',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: [
      '#인천',
      '#여행',
      '#태그가 길어지면 자르지말고 그냥 길게',
      '#태그가 길어지면 자르지말고 그냥 길게',
      '#태그',
      '#태그',
      '#태그',
    ],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행'],
  },
  {
    id: id++,
    ImageUrl: '',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행', '#태그'],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행'],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title:
      '제목 테스트 해야함 너무 길면 잘라야함. 잘라지나확인해보자@@@@@@@@@@@@',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: [
      '#인천',
      '#여행',
      '#태그가 길어지면 자르지말고 그냥 길게',
      '#태그가 길어지면 자르지말고 그냥 길게',
      '#태그',
      '#태그',
      '#태그',
    ],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행'],
  },
  {
    id: id++,
    ImageUrl: '',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행', '#태그'],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행'],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title:
      '제목 테스트 해야함 너무 길면 잘라야함. 잘라지나확인해보자@@@@@@@@@@@@',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: [
      '#인천',
      '#여행',
      '#태그가 길어지면 자르지말고 그냥 길게',
      '#태그가 길어지면 자르지말고 그냥 길게',
      '#태그',
      '#태그',
      '#태그',
    ],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행'],
  },
  {
    id: id++,
    ImageUrl: '',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행', '#태그'],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행'],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title:
      '제목 테스트 해야함 너무 길면 잘라야함. 잘라지나확인해보자@@@@@@@@@@@@',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: [
      '#인천',
      '#여행',
      '#태그가 길어지면 자르지말고 그냥 길게',
      '#태그가 길어지면 자르지말고 그냥 길게',
      '#태그',
      '#태그',
      '#태그',
    ],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행'],
  },
  {
    id: id++,
    ImageUrl: '',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행', '#태그'],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행'],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title:
      '제목 테스트 해야함 너무 길면 잘라야함. 잘라지나확인해보자@@@@@@@@@@@@',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: [
      '#인천',
      '#여행',
      '#태그가 길어지면 자르지말고 그냥 길게',
      '#태그가 길어지면 자르지말고 그냥 길게',
      '#태그',
      '#태그',
      '#태그',
    ],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행'],
  },
  {
    id: id++,
    ImageUrl: '',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행', '#태그'],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행'],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title:
      '제목 테스트 해야함 너무 길면 잘라야함. 잘라지나확인해보자@@@@@@@@@@@@',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: [
      '#인천',
      '#여행',
      '#태그가 길어지면 자르지말고 그냥 길게',
      '#태그가 길어지면 자르지말고 그냥 길게',
      '#태그',
      '#태그',
      '#태그',
    ],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title: '우선 Like 수로 페이지네이션 확인해봄 1씩증가',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행'],
  },
  {
    id: id++,
    ImageUrl: '',
    Like: Like++,
    Title: '총 데이터는 80개로 만들어놨음. 10개씩, 8페이지',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행', '#태그'],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행'],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title:
      '제목 테스트 해야함 너무 길면 잘라야함. 잘라지나확인해보자@@@@@@@@@@@@',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: [
      '#인천',
      '#여행',
      '#태그가 길어지면 자르지말고 그냥 길게',
      '#태그가 길어지면 자르지말고 그냥 길게',
      '#태그',
      '#태그',
      '#태그',
    ],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행'],
  },
  {
    id: id++,
    ImageUrl: '',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행', '#태그'],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행'],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title:
      '제목 테스트 해야함 너무 길면 잘라야함. 잘라지나확인해보자@@@@@@@@@@@@',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: [
      '#인천',
      '#여행',
      '#태그가 길어지면 자르지말고 그냥 길게',
      '#태그가 길어지면 자르지말고 그냥 길게',
      '#태그',
      '#태그',
      '#태그',
    ],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행'],
  },
  {
    id: id++,
    ImageUrl: '',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행', '#태그'],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행'],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title:
      '제목 테스트 해야함 너무 길면 잘라야함. 잘라지나확인해보자@@@@@@@@@@@@',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: [
      '#인천',
      '#여행',
      '#태그가 길어지면 자르지말고 그냥 길게',
      '#태그가 길어지면 자르지말고 그냥 길게',
      '#태그',
      '#태그',
      '#태그',
    ],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행'],
  },
  {
    id: id++,
    ImageUrl: '',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행', '#태그'],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행'],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title:
      '제목 테스트 해야함 너무 길면 잘라야함. 잘라지나확인해보자@@@@@@@@@@@@',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: [
      '#인천',
      '#여행',
      '#태그가 길어지면 자르지말고 그냥 길게',
      '#태그가 길어지면 자르지말고 그냥 길게',
      '#태그',
      '#태그',
      '#태그',
    ],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행'],
  },
  {
    id: id++,
    ImageUrl: '',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행', '#태그'],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행'],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title:
      '제목 테스트 해야함 너무 길면 잘라야함. 잘라지나확인해보자@@@@@@@@@@@@',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: [
      '#인천',
      '#여행',
      '#태그가 길어지면 자르지말고 그냥 길게',
      '#태그가 길어지면 자르지말고 그냥 길게',
      '#태그',
      '#태그',
      '#태그',
    ],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행'],
  },
  {
    id: id++,
    ImageUrl: '',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행', '#태그'],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행'],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title:
      '제목 테스트 해야함 너무 길면 잘라야함. 잘라지나확인해보자@@@@@@@@@@@@',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: [
      '#인천',
      '#여행',
      '#태그가 길어지면 자르지말고 그냥 길게',
      '#태그가 길어지면 자르지말고 그냥 길게',
      '#태그',
      '#태그',
      '#태그',
    ],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행'],
  },
  {
    id: id++,
    ImageUrl: '',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행', '#태그'],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행'],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title:
      '제목 테스트 해야함 너무 길면 잘라야함. 잘라지나확인해보자@@@@@@@@@@@@',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: [
      '#인천',
      '#여행',
      '#태그가 길어지면 자르지말고 그냥 길게',
      '#태그가 길어지면 자르지말고 그냥 길게',
      '#태그',
      '#태그',
      '#태그',
    ],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행'],
  },
  {
    id: id++,
    ImageUrl: '',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행', '#태그'],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행'],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title:
      '제목 테스트 해야함 너무 길면 잘라야함. 잘라지나확인해보자@@@@@@@@@@@@',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: [
      '#인천',
      '#여행',
      '#태그가 길어지면 자르지말고 그냥 길게',
      '#태그가 길어지면 자르지말고 그냥 길게',
      '#태그',
      '#태그',
      '#태그',
    ],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행'],
  },
  {
    id: id++,
    ImageUrl: '',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행', '#태그'],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행'],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title:
      '제목 테스트 해야함 너무 길면 잘라야함. 잘라지나확인해보자@@@@@@@@@@@@',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: [
      '#인천',
      '#여행',
      '#태그가 길어지면 자르지말고 그냥 길게',
      '#태그가 길어지면 자르지말고 그냥 길게',
      '#태그',
      '#태그',
      '#태그',
    ],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행'],
  },
  {
    id: id++,
    ImageUrl: '',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행', '#태그'],
  },
  {
    id: id++,
    ImageUrl: 'favicon.ico',
    Like: Like++,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행'],
  },
];

export const totalItemsCount = dailyListInfo.length;