export type DailyListInfoType = {
  id: number;
  ImageUrl: string;
  Like: number;
  Title: string;
  Writer: string;
  Date: Date;
  Comment: number;
  Tags: string[];
};
export const dailyListInfo: DailyListInfoType[] = [
  {
    id: 123,
    ImageUrl: 'favicon.ico',
    Like: 12,
    Title:
      '제목 테스트 해야함 너무 길면 잘라야함. 잘라지나확인해보자@@@@@@@@@@@@',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: [
      '#인천',
      '#여행',
      '#태그가 길어지면 자르지말고 그냥 길게',
      '#태그가 길어지면 자르지말고 그냥 길게',
      '#태그',
      '#태그',
      '#태그',
    ],
  },
  {
    id: 45,
    ImageUrl: 'favicon.ico',
    Like: 12,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행'],
  },
  {
    id: 6,
    ImageUrl: '',
    Like: 12,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행', '#태그'],
  },
  {
    id: 7,
    ImageUrl: 'favicon.ico',
    Like: 12,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행'],
  },
  {
    id: 8,
    ImageUrl: '',
    Like: 12,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행'],
  },
  {
    id: 9,
    ImageUrl: 'favicon.ico',
    Like: 12,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행'],
  },
  {
    id: 51893,
    ImageUrl: 'favicon.ico',
    Like: 12,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행'],
  },
  {
    id: 51891,
    ImageUrl: 'favicon.ico',
    Like: 12,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행'],
  },
  {
    id: 51892,
    ImageUrl: 'favicon.ico',
    Like: 12,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행'],
  },
  {
    id: 51894,
    ImageUrl: 'favicon.ico',
    Like: 12,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행'],
  },
  {
    id: 51895,
    ImageUrl: 'favicon.ico',
    Like: 12,
    Title: '제목 테스트 해야함 너무 길면 잘라야함.',
    Writer: '글쓴이닉네임',
    Date: new Date(),
    Comment: 12,
    Tags: ['#인천', '#여행'],
  },
];
